### PR TITLE
feat: Add optional enableLogs parameter

### PR DESCRIPTION
**Pull request by giplash**
Hi, Derek!
I suggest you to add optional parameter enableLogs to functions that currently use console.log to provide an opportunity to users keep their consoles clear.

### CODE REVIEW

**Comment by giplash** [comment]
Hi Derek, please leave some comments

**Comment by derekfinlinson** [comment]
I'm not sure how useful that is. You really need some log messages so you know what's happening with the upload and if it was successful or not. What might make sense is to add a log level instead so you can pick between verbose, minimal, error, etc.

**Comment by giplash** [comment]
Thanks for answering. Do you mean log level property in config?

**Comment by derekfinlinson** [comment]
My thought is they would pass in either "Verbose", "Error", or "Info" or something and that would determine which messages get logged. Some messages would always be logged, others only if the log level was verbose, etc. So you're "enableLogs" would be a log level enum instead.

**Pull request closed without merging**
