### PR TITLE
fix import from xrm-webapi

### PR DESCRIPTION
**Pull request by giplash**
There is a problem in latest version, code doesn't work in node environment.
I added conditional import from xrm-webapi.

### CODE REVIEW

**Comment by derekfinlinson** [comment]
This is meant to run from node only so just switching the import to `xrm-webapi/dist/xrm-webapi-node` should be sufficient

**Comment by giplash** [comment]
Exactly, fixed

**Comment by derekfinlinson** [comment]
Thanks!

**Pull request merged**
